/**
 * @file edhoc_hw.c
 * @brief EDHOC Hardware Accelerator Driver Implementation
 *
 * Driver for the EDHOC+OSCORE hardware accelerator.
 */

#include "edhoc_hw.h"
#include <string.h>

/* Forward declare kprintf for debugging */
extern void kprintf(const char* fmt, ...);

/* rdcycle for timing */
static inline unsigned long rdcycle(void) {
    unsigned long cycles;
    asm volatile ("rdcycle %0" : "=r" (cycles));
    return cycles;
}

/* ========================================================================== */
/* Basic Control Functions                                                    */
/* ========================================================================== */

void edhoc_hw_reset(void* base) {
    /* Set reset bit */
    _REG32(base, EDHOC_REG_CONTROL) = EDHOC_CTRL_RESET;
    
    /* Small delay */
    for (volatile int i = 0; i < 10; i++);
    
    /* Clear reset bit */
    _REG32(base, EDHOC_REG_CONTROL) = 0x00;
}

void edhoc_hw_init(void* base, const edhoc_params_t* params) {
    int i;
    
    /* Reset first */
    edhoc_hw_reset(base);
    
    /* Check if TRNG is enabled (bypass mode disabled) */
    uint32_t trng_control = _REG32(base, EDHOC_REG_TRNG_CONTROL);
    int trng_enabled = (trng_control & EDHOC_TRNG_EN) && !(trng_control & EDHOC_XDRBG_BYPASS);
    
    /* Write ephemeral key only in bypass mode (TRNG disabled) */
    if (!trng_enabled) {
        /* Hardware expects: reg[0] = bytes[0:3], reg[1] = bytes[4:7], etc. */
        for (i = 0; i < 8; i++) {
            uint32_t val = ((uint32_t)params->ephemeral_key[i*4 + 3]) |
                           ((uint32_t)params->ephemeral_key[i*4 + 2] << 8) |
                           ((uint32_t)params->ephemeral_key[i*4 + 1] << 16) |
                           ((uint32_t)params->ephemeral_key[i*4 + 0] << 24);
            _REG32(base, EDHOC_REG_EPHEMERAL_KEY + (7 - i)*4) = val;
        }
    }
    /* If TRNG enabled: ephemeral_key will be generated by TRNG+XDRBG */
    
    /* Write params_0: c_x[7:0], method[15:8], suite[23:16], id_cred_psk[31:24] */
    _REG32(base, EDHOC_REG_PARAMS_0) = 
        ((uint32_t)params->c_x) |
        ((uint32_t)params->method << 8) |
        ((uint32_t)params->suite << 16) |
        ((uint32_t)params->id_cred_psk << 24);
    
    /* Write params_1: kid_initiator[7:0], kid_responder[15:8] */
    _REG32(base, EDHOC_REG_PARAMS_1) = 
        ((uint32_t)params->kid_initiator) |
        ((uint32_t)params->kid_responder << 8);
    
    /* Write id_initiator (64-bit = 2x32-bit) */
    _REG32(base, EDHOC_REG_ID_INITIATOR + 4) = 
        ((uint32_t)params->id_initiator[3]) |
        ((uint32_t)params->id_initiator[2] << 8) |
        ((uint32_t)params->id_initiator[1] << 16) |
        ((uint32_t)params->id_initiator[0] << 24);
    _REG32(base, EDHOC_REG_ID_INITIATOR + 0) = 
        ((uint32_t)params->id_initiator[7]) |
        ((uint32_t)params->id_initiator[6] << 8) |
        ((uint32_t)params->id_initiator[5] << 16) |
        ((uint32_t)params->id_initiator[4] << 24);
    
    /* Write id_responder (64-bit = 2x32-bit) */
    _REG32(base, EDHOC_REG_ID_RESPONDER + 4) = 
        ((uint32_t)params->id_responder[3]) |
        ((uint32_t)params->id_responder[2] << 8) |
        ((uint32_t)params->id_responder[1] << 16) |
        ((uint32_t)params->id_responder[0] << 24);
    _REG32(base, EDHOC_REG_ID_RESPONDER + 0) = 
        ((uint32_t)params->id_responder[7]) |
        ((uint32_t)params->id_responder[6] << 8) |
        ((uint32_t)params->id_responder[5] << 16) |
        ((uint32_t)params->id_responder[4] << 24);
}

int edhoc_hw_start_initiator(void* base) {
    /* Set start and initiator bits */
    _REG32(base, EDHOC_REG_CONTROL) = EDHOC_CTRL_START | EDHOC_CTRL_INITIATOR;
    return 0;
}

int edhoc_hw_start_responder(void* base) {
    /* Set start bit only (initiator=0 means responder) */
    _REG32(base, EDHOC_REG_CONTROL) = EDHOC_CTRL_START;
    return 0;
}

/* ========================================================================== */
/* Status Functions                                                           */
/* ========================================================================== */

int edhoc_hw_wait_msg_ready(void* base) {
    uint32_t status;
    unsigned long timeout = 1000000;
    
    do {
        status = _REG32(base, EDHOC_REG_STATUS);
        if (status & EDHOC_STATUS_ERROR) {
            return -1;
        }
        timeout--;
    } while (!(status & EDHOC_STATUS_MSG_READY) && timeout > 0);
    
    return (timeout > 0) ? 0 : -1;
}

int edhoc_hw_get_current_msg(void* base) {
    uint32_t status = _REG32(base, EDHOC_REG_STATUS);
    return (status & EDHOC_STATUS_CURRENT_MSG_MASK) >> EDHOC_STATUS_CURRENT_MSG_SHIFT;
}

int edhoc_hw_wait_output_valid(void* base) {
    uint32_t status;
    unsigned long timeout = 1000000;
    
    do {
        status = _REG32(base, EDHOC_REG_STATUS);
        if (status & EDHOC_STATUS_ERROR) {
            return -1;
        }
        timeout--;
    } while (!(status & EDHOC_STATUS_OUTPUT_VALID) && timeout > 0);
    
    return (timeout > 0) ? 0 : -1;
}

int edhoc_hw_wait_done(void* base) {
    uint32_t status;
    unsigned long timeout = 10000000;
    
    do {
        status = _REG32(base, EDHOC_REG_STATUS);
        if (status & EDHOC_STATUS_ERROR) {
            return -1;
        }
        timeout--;
    } while (!(status & EDHOC_STATUS_DONE) && timeout > 0);
    
    /* Clear sticky flags after reading */
    if (timeout > 0) {
        _REG32(base, EDHOC_REG_CONTROL) = EDHOC_CTRL_CLEAR_FLAGS;
    }
    
    return (timeout > 0) ? 0 : -1;
}

int edhoc_hw_oscore_keys_valid(void* base) {
    uint32_t status = _REG32(base, EDHOC_REG_STATUS);
    return (status & EDHOC_STATUS_OSCORE_KEYS_VALID) ? 1 : 0;
}

/* ========================================================================== */
/* Data I/O Functions                                                         */
/* ========================================================================== */

void edhoc_hw_write_data_in(void* base, const uint8_t* data, uint8_t len) {
    int i, j;
    uint32_t val;
    
    /* Write data in 32-bit chunks */
    for (i = 0; i < 10; i++) {
        val = 0;
        for (j = 0; j < 4; j++) {
            int idx = i*4 + (3-j);
            if (idx < len) {
                val |= ((uint32_t)data[idx] << (j*8));
            }
        }
        _REG32(base, EDHOC_REG_DATA_IN + ((9-i)*4)) = val;
    }
}

void edhoc_hw_set_msg_valid(void* base) {
    /* Clear msg_ready sticky flag before pulsing msg_valid */
    _REG32(base, EDHOC_REG_CONTROL) = EDHOC_CTRL_CLEAR_FLAGS;
    
    /* Write 1 to msg_valid register to pulse signal */
    _REG32(base, EDHOC_REG_MSG_VALID) = 1;
}

void edhoc_hw_set_output_ack(void* base) {
    /* Write 1 to output_ack register to pulse signal
     * This tells the hardware that output has been captured,
     * which clears output_valid in hardware */
    _REG32(base, EDHOC_REG_OUTPUT_ACK) = 1;
}

void edhoc_hw_read_data_out(void* base, uint8_t* data, uint8_t* len) {
    int i, j;
    uint32_t val;
    
    /* Determine length based on current message number BEFORE acknowledging */
    int msg_num = edhoc_hw_get_current_msg(base);

    /* Read data in 32-bit chunks */
    for (i = 0; i < 10; i++) {
        val = _REG32(base, EDHOC_REG_DATA_OUT + (i*4));
        for (j = 0; j < 4; j++) {
            int idx = i*4 + (3-j);
            if (idx < 40) {
                data[idx] = (uint8_t)(val >> (j*8));
            }
        }
    }
    
    /* Send output_ack to clear output_valid in hardware */
    edhoc_hw_set_output_ack(base);
    
    /* Set length based on message number */
    if (len) {
        // kprintf("Current msg num: %d\r\n", msg_num);
        switch (msg_num) {
            case 1: *len = EDHOC_MSG1_SIZE; break;
            case 2: *len = EDHOC_MSG2_SIZE; break;
            case 3: *len = EDHOC_MSG3_SIZE; break;
            case 0: *len = EDHOC_MSG4_SIZE; break;
            default: *len = 0; break;
        }
    }
}

/* ========================================================================== */
/* OSCORE Context Functions                                                   */
/* ========================================================================== */

void edhoc_hw_get_oscore_context(void* base, oscore_context_t* ctx) {
    /* Check if OSCORE keys are valid */
    ctx->oscore_ready = edhoc_hw_oscore_keys_valid(base) ? 1 : 0;
}

// void edhoc_hw_print_context(const oscore_context_t* ctx) {
//     kprintf("OSCORE Context:\r\n");
//     kprintf("  Ready: %s\r\n", ctx->oscore_ready ? "YES" : "NO");
//     kprintf("  (All keys remain internal to hardware)\r\n");
// }
/* ========================================================================== */
/* AEAD Functions                                                             */
/* ========================================================================== */
static void edhoc_hw_write_aead_params(void* base, const aead_params_t* params) {
    int i;
    uint32_t val;
    
    /* Write sender_id (8-bit) */
    _REG32(base, EDHOC_REG_AEAD_SENDER_ID) = (uint32_t)params->sender_id;
    
    /* Write partial_iv (40-bit, 2x32-bit registers) */
    /* partial_iv[0] is MSB, partial_iv[4] is LSB */
    /* Register 0x104: partial_iv[39:8] in bits [31:0] */
    val = ((uint32_t)params->partial_iv[0] << 24) |
          ((uint32_t)params->partial_iv[1] << 16) |
          ((uint32_t)params->partial_iv[2] << 8) |
          ((uint32_t)params->partial_iv[3]);
    _REG32(base, EDHOC_REG_AEAD_PARTIAL_IV) = val;
    /* Register 0x108: partial_iv[7:0] in bits [7:0] */
    _REG32(base, EDHOC_REG_AEAD_PARTIAL_IV + 4) = (uint32_t)params->partial_iv[4];
    
    /* Write AAD (128-bit) - FIX: reverse register indexing */
    for (i = 0; i < 4; i++) {
        val = ((uint32_t)params->aad[i*4 + 3]) |
              ((uint32_t)params->aad[i*4 + 2] << 8) |
              ((uint32_t)params->aad[i*4 + 1] << 16) |
              ((uint32_t)params->aad[i*4 + 0] << 24);
        _REG32(base, EDHOC_REG_AEAD_AAD +  (3 - i)*4) = val;  // Changed from (i*4)
    }
    
    /* Write lengths: aad_len[3:0], data_len[7:4] */
    _REG32(base, EDHOC_REG_AEAD_LENGTHS) = 
        ((uint32_t)params->aad_len & 0x0F) |
        (((uint32_t)params->data_len & 0x0F) << 4);
    
    /* Write data_in (128-bit) - FIX: reverse register indexing */
    for (i = 0; i < 4; i++) {
        val = ((uint32_t)params->data_in[i*4 + 3]) |
              ((uint32_t)params->data_in[i*4 + 2] << 8) |
              ((uint32_t)params->data_in[i*4 + 1] << 16) |
              ((uint32_t)params->data_in[i*4 + 0] << 24);
        _REG32(base, EDHOC_REG_AEAD_DATA_IN + (3 - i)*4) = val;  // Changed from (i*4)
    }
    
    /* Write expected tag for decryption (128-bit) - FIX: reverse register indexing */
    for (i = 0; i < 4; i++) {
        val = ((uint32_t)params->exp_tag[i*4 + 3]) |
              ((uint32_t)params->exp_tag[i*4 + 2] << 8) |
              ((uint32_t)params->exp_tag[i*4 + 1] << 16) |
              ((uint32_t)params->exp_tag[i*4 + 0] << 24);
        _REG32(base, EDHOC_REG_AEAD_EXP_TAG + (3 - i)*4) = val;  // Changed from (i*4)
    }
}

static void edhoc_hw_read_aead_result(void* base, aead_result_t* result) {
    int i;
    uint32_t val, status;
    
    /* Initialize result buffer to zeros */
    memset(result->data_out, 0, 16);
    memset(result->tag, 0, 16);
    
    /* Read data_out (128-bit) - FIX: reverse register indexing */
    for (i = 0; i < 4; i++) {
        val = _REG32(base, EDHOC_REG_AEAD_DATA_OUT + (3 - i)*4);  // Changed from (i*4)
        result->data_out[i*4 + 3] = (uint8_t)(val & 0xFF);
        result->data_out[i*4 + 2] = (uint8_t)((val >> 8) & 0xFF);
        result->data_out[i*4 + 1] = (uint8_t)((val >> 16) & 0xFF);
        result->data_out[i*4 + 0] = (uint8_t)((val >> 24) & 0xFF);
    }
    
    /* Read tag (128-bit) - FIX: reverse register indexing */
    for (i = 0; i < 4; i++) {
        val = _REG32(base, EDHOC_REG_AEAD_TAG + (3 - i)*4);  // Changed from (i*4)
        result->tag[i*4 + 3] = (uint8_t)(val & 0xFF);
        result->tag[i*4 + 2] = (uint8_t)((val >> 8) & 0xFF);
        result->tag[i*4 + 1] = (uint8_t)((val >> 16) & 0xFF);
        result->tag[i*4 + 0] = (uint8_t)((val >> 24) & 0xFF);
    }
    
    /* Read tag_valid from status */
    status = _REG32(base, EDHOC_REG_STATUS);
    result->tag_valid = (status & EDHOC_STATUS_AEAD_TAG_VALID) ? 1 : 0;
}

static int edhoc_hw_wait_aead_done(void* base) {
    uint32_t status;
    unsigned long timeout = 1000000;
    
    do {
        status = _REG32(base, EDHOC_REG_STATUS);
        timeout--;
    } while (!(status & EDHOC_STATUS_AEAD_DONE) && timeout > 0);
    
    /* Do NOT clear sticky flags here!
     * aead_tag_valid_sticky must remain set so read_aead_result can check it.
     * Stickies are cleared at the START of each encrypt/decrypt call instead. */
    
    return (timeout > 0) ? 0 : -1;
}

int edhoc_hw_aead_encrypt(void* base, const aead_params_t* params, aead_result_t* result) {
    uint32_t ctrl;
    
    /* Clear any previous sticky flags */
    _REG32(base, EDHOC_REG_CONTROL) = EDHOC_CTRL_CLEAR_FLAGS;
    
    /* Write AEAD parameters */
    edhoc_hw_write_aead_params(base, params);
    
    /* Set control: aead_start, aead_encrypt, use_sender_key */
    ctrl = EDHOC_CTRL_AEAD_START | EDHOC_CTRL_AEAD_ENCRYPT;
    if (params->use_sender_key) {
        ctrl |= EDHOC_CTRL_AEAD_USE_SENDER_KEY;
    }
    _REG32(base, EDHOC_REG_CONTROL) = ctrl;
    
    /* Wait for AEAD done */
    if (edhoc_hw_wait_aead_done(base) < 0) {
        return -1;
    }
    
    /* Read result */
    edhoc_hw_read_aead_result(base, result);
    
    return 0;
}

int edhoc_hw_aead_decrypt(void* base, const aead_params_t* params, aead_result_t* result) {
    uint32_t ctrl;
    
    /* Clear any previous sticky flags */
    _REG32(base, EDHOC_REG_CONTROL) = EDHOC_CTRL_CLEAR_FLAGS;
    
    /* Write AEAD parameters */
    edhoc_hw_write_aead_params(base, params);
    
    /* Set control: aead_start, NOT aead_encrypt, use_sender_key */
    ctrl = EDHOC_CTRL_AEAD_START;  /* encrypt=0 for decrypt */
    if (params->use_sender_key) {
        ctrl |= EDHOC_CTRL_AEAD_USE_SENDER_KEY;
    }
    _REG32(base, EDHOC_REG_CONTROL) = ctrl;
    
    /* Wait for AEAD done */
    if (edhoc_hw_wait_aead_done(base) < 0) {
        return -1;
    }
    
    /* Read result */
    edhoc_hw_read_aead_result(base, result);
    
    return result->tag_valid ? 0 : -1;
}

/* ========================================================================== */
/* Complete Handshake Functions                                               */
/* ========================================================================== */

int edhoc_hw_initiator_handshake(void* base, const edhoc_params_t* params,
                                  uint8_t* msg1_out, uint8_t* msg1_len,
                                  const uint8_t* msg2_in, uint8_t msg2_len,
                                  uint8_t* msg3_out, uint8_t* msg3_len,
                                  const uint8_t* msg4_in, uint8_t msg4_len,
                                  oscore_context_t* ctx) {
    /* Initialize */
    edhoc_hw_init(base, params);
    
    /* Start as initiator */
    edhoc_hw_start_initiator(base);
    
    /* Wait for MSG1 output */
    if (edhoc_hw_wait_output_valid(base) < 0) {
        return -1;
    }
    edhoc_hw_read_data_out(base, msg1_out, msg1_len);
    
    /* Wait for ready to receive MSG2 */
    if (edhoc_hw_wait_msg_ready(base) < 0) {
        return -1;
    }
    
    /* Write MSG2 and signal valid */
    edhoc_hw_write_data_in(base, msg2_in, msg2_len);
    edhoc_hw_set_msg_valid(base);
    
    /* Wait for MSG3 output */
    if (edhoc_hw_wait_output_valid(base) < 0) {
        return -1;
    }
    edhoc_hw_read_data_out(base, msg3_out, msg3_len);
    
    /* Wait for ready to receive MSG4 */
    if (edhoc_hw_wait_msg_ready(base) < 0) {
        return -1;
    }
    
    /* Write MSG4 and signal valid */
    edhoc_hw_write_data_in(base, msg4_in, msg4_len);
    edhoc_hw_set_msg_valid(base);
    
    /* Wait for done */
    if (edhoc_hw_wait_done(base) < 0) {
        return -1;
    }
    
    /* Get OSCORE context (keys stay internal) */
    if (edhoc_hw_oscore_keys_valid(base)) {
        edhoc_hw_get_oscore_context(base, ctx);
    } else {
        return -1;
    }
    
    return 0;
}

int edhoc_hw_responder_handshake(void* base, const edhoc_params_t* params,
                                  const uint8_t* msg1_in, uint8_t msg1_len,
                                  uint8_t* msg2_out, uint8_t* msg2_len,
                                  const uint8_t* msg3_in, uint8_t msg3_len,
                                  uint8_t* msg4_out, uint8_t* msg4_len,
                                  oscore_context_t* ctx) {
    /* Initialize */
    edhoc_hw_init(base, params);
    
    /* Start as responder */
    edhoc_hw_start_responder(base);
    
    /* Wait for ready to receive MSG1 */
    if (edhoc_hw_wait_msg_ready(base) < 0) {
        return -1;
    }
    
    /* Write MSG1 and signal valid */
    edhoc_hw_write_data_in(base, msg1_in, msg1_len);
    edhoc_hw_set_msg_valid(base);
    
    /* Wait for MSG2 output */
    if (edhoc_hw_wait_output_valid(base) < 0) {
        return -1;
    }
    edhoc_hw_read_data_out(base, msg2_out, msg2_len);
    
    /* Wait for ready to receive MSG3 */
    if (edhoc_hw_wait_msg_ready(base) < 0) {
        return -1;
    }
    
    /* Write MSG3 and signal valid */
    edhoc_hw_write_data_in(base, msg3_in, msg3_len);
    edhoc_hw_set_msg_valid(base);
    
    /* Wait for MSG4 output */
    if (edhoc_hw_wait_output_valid(base) < 0) {
        return -1;
    }
    edhoc_hw_read_data_out(base, msg4_out, msg4_len);
    
    /* Wait for done */
    if (edhoc_hw_wait_done(base) < 0) {
        return -1;
    }
    
    /* Get OSCORE context (keys stay internal) */
    if (edhoc_hw_oscore_keys_valid(base)) {
        edhoc_hw_get_oscore_context(base, ctx);
    } else {
        return -1;
    }
    
    return 0;
}

/* ========================================================================== */
/* Self-Test Function                                                         */
/* ========================================================================== */

// void edhoc_hw_selftest(void* base) {
//     uint32_t status;
    
//     kprintf("\r\n=== EDHOC Hardware Self-Test ===\r\n");
    
//     /* Reset and check status */
//     edhoc_hw_reset(base);
//     status = _REG32(base, EDHOC_REG_STATUS);
//     kprintf("After reset, status: 0x%08x\r\n", status);
    
//     /* Verify register read/write */
//     kprintf("Testing register access...\r\n");
    
//     /* Write a test pattern to ephemeral_key[0] */
//     _REG32(base, EDHOC_REG_EPHEMERAL_KEY) = 0xDEADBEEF;
//     uint32_t val = _REG32(base, EDHOC_REG_EPHEMERAL_KEY);
//     if (val == 0xDEADBEEF) {
//         kprintf("  ephemeral_key[0]: PASS\r\n");
//     } else {
//         kprintf("  ephemeral_key[0]: FAIL (got 0x%08x)\r\n", val);
//     }
    
//     /* Write test pattern to params_0 */
//     _REG32(base, EDHOC_REG_PARAMS_0) = 0x07042D01;  /* suite=7, method=4, c_x=0x2D, id_cred=1 */
//     val = _REG32(base, EDHOC_REG_PARAMS_0);
//     if (val == 0x07042D01) {
//         kprintf("  params_0: PASS\r\n");
//     } else {
//         kprintf("  params_0: FAIL (got 0x%08x)\r\n", val);
//     }
    
//     /* Reset to clean state */
//     edhoc_hw_reset(base);
    
//     kprintf("=== Self-Test Complete ===\r\n\r\n");
// }
